import { Inter } from "next/font/google";
import "./globals.css";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav style={{
          position: 'fixed',
          top: 0,
          left: 0,
          width: '100%',
          backgroundColor: '#ffffff', // Adjust color as needed
          zIndex: 1000,
          boxShadow: '0 2px 4px rgba(0,0,0,0.1)', // Optional shadow
          padding: '1rem 1rem', // Adjust padding as needed
        }}>
          <div className="container mx-auto flex justify-between">
            <div className="flex space-x-12">
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 198.96 50.44" width="70" height="24" role="img" class="svg" aria-label="Trulia Logo" aria-hidden="false"><path d="M147.71 11a5.51 5.51 0 1 0-5.5-5.51 5.51 5.51 0 0 0 5.5 5.51zm4.99 29.56V14.64h-15.5v9.28h6.22v25.92h15.49v-9.28h-6.21zm-26.49 0V2.54h-15.49v9.28h6.21v28.74h-6.21v9.28h21.7v-9.28h-6.21zM60.25 14.52h-2.81a12.17 12.17 0 0 0-10.75 5.39l-1.89-5.27h-9.11v9.28H40v25.92h9.28V31.72a8.16 8.16 0 0 1 8.16-8.16h2.81zm42.98 18.35V14.64H94V33.2a8.29 8.29 0 0 1-16.58 0V14.64h-9.33v18.23a17.57 17.57 0 0 0 35.14 0zM27.6 23.92v-9.28H15.49V3.28H6.22v11.36H0v9.28h6.22v8.92a17.56 17.56 0 0 0 17.56 17.57A17.74 17.74 0 0 0 27.6 50v-9.17a9.28 9.28 0 0 1-3.18.56 8.78 8.78 0 0 1-8.93-8.61v-8.86zm162.09-9.28v3.5a13.08 13.08 0 0 0-9.14-4h-.72c-9.17 0-16.6 8.12-16.6 18.15s7.43 18.19 16.6 18.15h.72a13.08 13.08 0 0 0 9.14-4v3.5H199v-35.3zm-8.81 26.82a9.06 9.06 0 0 1-8.88-9.23 8.85 8.85 0 1 1 17.69 0 9 9 0 0 1-8.81 9.23z"></path></svg>
              {/* <Button>Buy</Button> */}
              <DropdownMenu>
                <DropdownMenuTrigger>
                  <Button>Buy</Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent>
                  <DropdownMenuLabel>My Account</DropdownMenuLabel>
                  <DropdownMenuSeparator />
                  <DropdownMenuItem>Profile</DropdownMenuItem>
                  <DropdownMenuItem>Billing</DropdownMenuItem>
                  <DropdownMenuItem>Team</DropdownMenuItem>
                  <DropdownMenuItem>Subscription</DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>

              <Button>Rent</Button>
              <Button>Mortgage</Button>
            </div>

            {/* Right links */}
            <div className="flex space-x-12">
              <Button>Saved Homes</Button>
              <Button>Saved Search</Button>
              <Button variant={"outline"}>Sign up or Log in</Button>
              <svg viewBox="0 0 32 32" xmlns="http://www.w3.org/2000/svg" width="1.5em" height="1.5em" role="img" aria-label="" aria-hidden="true" class="w_24 h_24 svg"><path d="M5.404 9.942v-2.66h21.142v2.66H5.404zm0 7.348v-2.66h21.142v2.66H5.404zm0 7.348v-2.66h21.142v2.66H5.404z" fill="#869099"></path></svg>
            </div>
          </div>
        </nav>
        <div style={{ paddingTop: '5rem' }}>{children}</div>
      </body>
    </html>
  );
}
